cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<pk>/', views.OrderDetailView.as_view(), name='order-detail'),

]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/views.py
from django.http import HttpResponse
import datetime
import json
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.http import request
from django.shortcuts import get_object_or_404, reverse, redirect
from django.utils import timezone
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from .forms import (AddToCartForm, AddressForm, CouponForm,)
from .models import (Coupon, Product, OrderItem,
                     Address, Payment, Order, Category)
from core.models import Customer
from .utils import get_or_set_order_session


class ProductListView(generic.ListView):
    template_name = 'cart/product_list.html'

    def get_queryset(self):
        qs = Product.objects.filter(active=True)
        category = self.request.GET.get('category', None)
        if category:
            qs = qs.filter(Q(primary_category__name=category) | Q(
                secondary_categories__name=category)).distinct()
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context.update({
            "categories": Category.objects.values("name")
        })
        return context


class ProductDetailView(generic.FormView):
    template_name = 'cart/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,
            size=form.cleaned_data['size'],
        )

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()

        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context


class CartView(generic.FormView):
    template_name = "cart/cart.html"
    form_class = CouponForm

    def get_success_url(self):
        return reverse("cart:summary")

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        # context["form"] = self.form_class

        return context

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        code = form.cleaned_data.get('coupon_code')
        order.coupon = Coupon.objects.get(code=code)
        order.save()
        messages.info(self.request, "Kod został dodany poprawnie")
        return super(CartView, self).form_valid(form)


class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:summary")


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("cart:summary")


class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("cart:summary")


class CheckoutView(generic.FormView):
    template_name = 'cart/checkout.html'
    form_class = AddressForm

    def get_success_url(self):
        return reverse("cart:payment")

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        try:
            customer = Customer.objects.get(user=self.request.user)
        except Customer.DoesNotExist:
            customer = None
        except TypeError:
            customer = None
            # try:
            #     customer = Customer.objects.get(email=form.cleaned_data['email_shipping'])
            # except Customer.DoesNotExist:
            #     customer = Customer.objects.create(
            #         email=form.cleaned_data['email_shipping'],
            #         first_name=form.cleaned_data['first_name_shipping'],
            #         last_name=form.cleaned_data['last_name_shipping'],
            #         phone_number=form.cleaned_data['phone_number_shipping']
            #     )
        selected_shipping_address = form.cleaned_data.get(
            'selected_shipping_address')
        selected_billing_address = form.cleaned_data.get(
            'selected_billing_address')
        is_addresses_same = form.cleaned_data.get(
            'is_addresses_same')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type='S',
                customer=customer,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                address_line_2=form.cleaned_data['shipping_address_line_2'],
                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],
            )
            order.shipping_address = address

        if is_addresses_same:
            address = order.shipping_address
            order.billing_address = Address.objects.create(
                address_type='B',
                customer=customer,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                address_line_2=form.cleaned_data['shipping_address_line_2'],
                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],
            )

        else:
            if selected_billing_address:
                order.billing_address = selected_billing_address
            else:

                address = Address.objects.create(
                    address_type='B',
                    customer=customer,
                    address_line_1=form.cleaned_data['billing_address_line_1'],
                    address_line_2=form.cleaned_data['billing_address_line_2'],
                    zip_code=form.cleaned_data['billing_zip_code'],
                    city=form.cleaned_data['billing_city'],
                )
                order.billing_address = address

        order.save()
        messages.info(
            self.request, "You have successfully added your addresses")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class PaymentView(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context["PAYPAL_CLIENT_ID"] = settings.PAYPAL_CLIENT_ID
        context['order'] = get_or_set_order_session(self.request)
        context['CALLBACK_URL'] = self.request.build_absolute_uri(
            reverse("cart:thank-you"))
        return context


class ConfirmOrderView(generic.View):
    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        payment = Payment.objects.create(
            order=order,
            successful=True,
            raw_response=json.dumps(body),
            amount=float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='PayPal'
        )
        order.ordered = True
        order.ordered_date = datetime.date.today()
        order.save()
        return JsonResponse({"data": "Success"})


class ThankYouView(generic.TemplateView):
    template_name = 'cart/thanks.html'


class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'order.html'
    queryset = Order.objects.all()
    context_object_name = 'order'

templates/cart/cart.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Koszyk</strong>
            </div>
        </div>
    </div>
</div>


<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="site-blocks-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Zdjęcie</th>
                                <th>Produkt</th>
                                <th>Cena</th>
                                <th>Ilość</th>
                                <th>Razem</th>
                                <th>Akcje</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{request.scheme}}://{{request.META.HTTP_HOST}}{{ item.product.imageURL }}" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{ item.product.title }}</h2>
                                    <small>Rozmiar: {{ item.size.size }}</small>
                                    
                                </td>
                                <td>{{ item.product.get_price }} PLN</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <a href="{% url 'cart:decrease-quantity' item.id %}"
                                                class="btn btn-outline-primary">
                                                &minus;
                                            </a>
                                        </div>
                                        <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                                        <div class="input-group-append">
                                            <a href="{% url 'cart:increase-quantity' item.id %} "
                                                class="btn btn-outline-primary">
                                                &plus;
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    {{ item.get_total_item_price }} PLN
                                </td>
                                <td>
                                    <a href="{% url 'cart:remove-from-cart' item.id %}"
                                        class="btn btn-primary btn-sm">X</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colSpan='6'>
                                    Nie masz jeszcze nic w koszyku.
                                    <a href="{% url 'cart:product-list' %}">Kontynuj Zakupy</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        {% if order.items.count > 0 %}
        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-12">
                        <a class="btn btn-outline-primary btn-sm btn-block"
                            href="{% url 'cart:product-list' %}">Kontynuj Zakupy</a>
                    </div>
                </div>
            </div>

            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Suma Koszyka</h3>
                            </div>
                        </div>
                        
                        <div class="row mb-3 d-flex align-items-center">
                            <div class="col-md-12">
                                <!-- Coupon Form -->
                                <form method="POST">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button type="submit" class="form-group btn btn-primary btn-block">
                                        Dodaj Kupon
                                    </button>
                                </form>
                            </div>
                        </div>
                        <hr />
                        <div class="row mb-3">
                            <div class="col-md-12 text-right">
                                <strong class="text-black">{{ order.subtotal_formatted }} PLN</strong>
                            </div>
                        </div>
                        {% if order.coupon%}
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">{{order.coupon.code}}</span>
                            </div>
                            <div class="col-md-6 text-right ">
                                <strong class="text-black font-weight-bold">-{{ order.coupon.percent }}%</strong>
                            </div>
                        </div>
                        <hr />
                        <div class="row mb-5">
                            <div class="col-md-12 text-right">
                                <strong class="text-black">{{ order.get_subtotal }} PLN</strong>
                            </div>
                        </div>
                        {% endif %}

  
                        {% if order.shipping_method%}
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">{{ order.shipping_method.provider }}</span>
                            </div>
                            <div class="col-md-6 text-right ">
                                <strong class="text-black">{{ order.shipping_method.price_formatted }} PLN</strong>
                            </div>
                        </div>
                        {% endif %}
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Razem</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">{{ order.get_total }} PLN</strong>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <a class="btn btn-primary btn-lg py-3 btn-block" href="{% url 'cart:checkout' %}">Zamawiam</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        {% endif %}

    </div>
</div>

{% endblock content %}

templates/cart/checkout.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a
                ><span class="mx-2 mb-0">/</span>
                <a href="{% url 'cart:summary' %}" class="text-black">Cart</a
                ><span class="mx-2 mb-0">/</span>
                <strong class="text-black">Checkout</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        {% if not order.items.all.exists %}
        <div class="row mb-5">
            <div class="col-md-12">
                Nie masz jeszcze nic w koszyku.
                <a href="{% url 'cart:product-list' %}">Kontynuj Zakupy</a>
            </div>
        </div>
        {% else %}
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-5 mb-md-0" id="form-row">
                    <h2 class="h3 mb-3 text-black text-center">
                        Dane do Wysyłki i Płatności
                    </h2>
                    <hr />
                    {{ form|crispy }}
                    <div class="form-group">
                        <button
                            type="submit"
                            class="btn btn-primary btn-lg py-3 btn-block"
                        >
                            Przejdź do płatnośći
                        </button>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <h2 class="h3 mb-3 text-black text-center">
                                Twoje Zamówienie
                            </h2>
                            <hr />
                            <div class="p-3 p-lg-5">
                                <table
                                    class="table site-block-order-table mb-5"
                                >
                                    <thead>
                                        <tr>
                                            <th>Produkt</th>
                                            <th>Razem</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in order.items.all %}
                                        <tr>
                                            <td>
                                                {{ item.product.title }} - {{item.size.size }}
                                                <strong class="mx-2">x</strong>
                                                {{ item.quantity }}
                                            </td>
                                            <td>
                                                {{ item.get_total_item_price }}
                                                PLN
                                            </td>
                                        </tr>
                                        {% endfor %} {% if order.coupon%}
                                        <tr>
                                            <td>
                                                <strong>{{ order.coupon.code}}</strong>
                                            </td>
                                            <td>
                                                <strong>-{{ order.coupon.percent}}%</strong>
                                            </td>
                                        </tr>
                                        {% endif %}
                                        <tr>
                                            <td></td>
                                            <td>
                                                {{ order.get_subtotal }} PLN
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <strong class="text-black font-weight-bold">
                                                    Zamówienie Razem
                                                </strong>

                                            </td>
                                            <td>
                                                <strong class="text-black font-weight-bold">
                                                    {{ order.get_total }} PLN
                                                </strong>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        {% endif %}
    </div>
</div>
<script>
    function toggle_billing_divinputs(is_addresses_same, billing_divinputs_id) {
        if (is_addresses_same.checked) {
            billing_divinputs_id.map(function (id) {
                document.getElementById(id).style.display = "none";
            });
        } else {
            billing_divinputs_id.map(function (id) {
                document.getElementById(id).style.display = "";
            });
        }
    }
    const is_addresses_same = document.getElementById("id_is_addresses_same");
    const billing_divinputs_id = [
        "div_id_billing_address_line_1",
        "div_id_billing_address_line_2",
        "div_id_billing_zip_code",
        "div_id_billing_city",
        "div_id_selected_billing_address",
        "div_id_first_name_billing",
        "div_id_last_name_billing",
        "div_id_email_billing",
        "div_id_phone_number_billing",
    ];

    toggle_billing_divinputs(is_addresses_same, billing_divinputs_id);

    is_addresses_same.addEventListener("change", function (e) {
        toggle_billing_divinputs(is_addresses_same, billing_divinputs_id);
    });
</script>
{% endblock content %}

templates/cart/payment.html
{% extends "base.html" %}

{% block content %}

<style>
    lds-ring {
        display: inline-block;
        position: relative;
        width: 80px;
        height: 80px;
    }

    .lds-ring div {
        box-sizing: border-box;
        display: block;
        position: absolute;
        width: 64px;
        height: 64px;
        margin: 8px;
        border: 8px solid rgb(155, 81, 81);
        border-radius: 50%;
        animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
        border-color: rgb(155, 81, 81) transparent transparent transparent;
    }

    .lds-ring div:nth-child(1) {
        animation-delay: -0.45s;
    }

    .lds-ring div:nth-child(2) {
        animation-delay: -0.3s;
    }

    .lds-ring div:nth-child(3) {
        animation-delay: -0.15s;
    }

    @keyframes lds-ring {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>

<div class='container'>
    {% if not order.items.all.exists %}
    <div class="row mb-5">
        <div class="col-md-12">
            Nie masz jeszcze nic w koszyku.
            <a href="{% url 'cart:product-list' %}">Kontynuj Zakupy</a>
        </div>
    </div>
    {% else %}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
                Your payment was successful.
            </div>
            <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
                Your payment failed. Please try again.
            </div>

            <div class="text-center py-3">
                <div id="loader" class="lds-ring" style="margin: auto; display: none;">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>

            <div id='paymentInfo'>
                <p>Order total: {{ order.get_total }}zł</p>
                <h4>Select a payment method</h4>
                <div>
                    {% comment %} <a href="{% url 'cart:payment-stripe' %}" class="btn btn-secondary btn-block mb-3">Stripe</a> {% endcomment %}
                </div>
                <div id="paypal-button-container"></div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}


{% block scripts %}

<script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=PLN">
</script>

<script>

    const loader = document.getElementById('loader');
    const paymentInfo = document.getElementById('paymentInfo');

    function toggleLoader(on) {
        loader.style.display = on === true ? "block" : "none";
        paymentInfo.style.display = on === true ? "none" : "block";
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function sendOrderConfirmed(details) {
        return fetch("{% url 'cart:confirm-order' %}", {
            method: "post",
            body: JSON.stringify(details),
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            }
        })
    }

    paypal.Buttons({
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        currency_code: 'PLN',
                        value: '{{ order.get_total }}'
                    }
                }]
            });
        },
        onApprove: function (data, actions) {
            toggleLoader(true);
            // This function captures the funds from the transaction.
            return actions.order.capture().then(function (details) {
                // This function shows a transaction success message to your buyer.
                sendOrderConfirmed(details).then(res => {
                    toggleLoader(false);
                    const alertSuccess = document.getElementById('alertSuccess');
                    alertSuccess.style.display = 'block';
                    setTimeout(function () {
                        window.location.replace("{{ CALLBACK_URL }}")
                    }, 3000);
                })
            })
                .catch(err => {
                    const alertFailure = document.getElementById('alertFailure');
                    alertFailure.style.display = 'block';
                })
                .finally(() => toggleLoader(false));
        }
    }).render('#paypal-button-container');
</script>

{% endblock scripts %}

templates/cart/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load cart_template_tags %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">{{ product.title }}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6">
                {% comment %} <img src="{{ product.image.url }}" class="img-fluid"> {% endcomment %}
                {% product_image_to_html product request %}
            </div>
            <div class="col-md-6">
                <h2 class="text-black">{{ product.title }}</h2>
                <p>{{ product.description }}</p>
                <p>Dostępne sztuki: {{ product.stock }} sztuk</p>
                {% if product.in_stock %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class="btn btn-sm btn-primary buy-now">Dodaj do Koszyka</button>
                </form>
                {% else %}
                <p>OUT OF STOCK :(</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}